name: ml_cpu
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
  - osmnx
dependencies:
  - jupyterlab-lsp
  - jupyterlab[version='>=4.1.0,<5.0.0a0']
  - python-lsp-server
  - python=3.9
  - pytorch
  - torchvision
  - matplotlib
  - pytest
  - jsonschema
  - osmnx
